name: "Hello World"
description: "Greet someone"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
runs:
  using: "composite"
  steps:
    - run: echo Hello Migrations.
      shell: bash
