name: Golang HTTP Server deployment with Liquibase migrations

on:
  push:
    branches: [master]

jobs:
  migrate-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Database migrations
        uses: ssitko/k8s-liquibase-test-deployment/.github/includes/actions/migrations@master
  deploy-appliaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Application packaging & deployment
        uses: ssitko/k8s-liquibase-test-deployment/.github/includes/actions/deployment@master
