name: Golang HTTP Server deployment with Liquibase migrations

on:
  push:
    branches: [master]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: test-cluster
  GKE_ZONE: europe-central2-a
  DEPLOYMENT_NAME: golang-test-deployment
  IMAGE: golang-test

jobs:
  database-migrations:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Database migrations
        uses: ./.github/workflows/includes/actions/migrations
  infrastructure-setup:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup GCP Bucket
        uses: ./.github/workflows/includes/actions/infrastructure
  application-deployment:
    environment: dev
    needs: [database-migrations, infrastructure-setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - run: |-
          gcloud auth list
