name: Golang HTTP Server deployment with Liquibase migrations

on:
  push:
    branches: [master]

jobs:
  database-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Database migrations
        uses: ./.github/workflows/includes/actions/migrations
  infrastructure-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup GCP Bucket
        uses: ./.github/workflows/includes/actions/infrastructure
  application-deployment:
    needs: [database-migrations, infrastructure-setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Application deployment
        uses: ./.github/workflows/includes/actions/deployment
      - name: Failure rollback
        if: ${{ failure() }}
        uses: ./.github/workflows/includes/actions/rollback
