name: Golang HTTP Server deployment with Liquibase migrations

on:
  push:
    branches: [master]

jobs:
  - name: Migrate database
    runs-on: ubuntu-latest
    uses: ./.github/includes/actions/migrations/action.yml

  - name: Application deployment
    runs-on: ubuntu-latest
    uses: ./.github/includes/actions/deployment/action.yml
