name: Golang HTTP Server deployment with Liquibase migrations

on:
  push:
    branches: [master]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: test-cluster
  GKE_ZONE: europe-central2-a
  DEPLOYMENT_NAME: golang-test-deployment
  IMAGE: golang-test

jobs:
  database-migrations:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Database migrations
        uses: ./.github/workflows/includes/actions/migrations
  infrastructure-setup:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup GCP Bucket
        uses: ./.github/workflows/includes/actions/infrastructure
  application-deployment:
    environment: dev
    needs: [database-migrations, infrastructure-setup]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - name: Auth to GKE
        uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
