name: Golang HTTP Server deployment with Liquibase migrations

on:
  push:
    branches: [master]

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/includes/actions/migrations

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/includes/actions/deployment
