name: Golang HTTP Server deployment with Liquibase migrations

on:
  push:
    branches: [master]

jobs:
  database-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Database migrations
        uses: ./.github/workflows/includes/actions/migrations
  application-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Application deployment
        uses: ./.github/workflows/includes/actions/deploymentx
        if: ${{ failure() }}
        run: echo Failure!
