name: Golang HTTP Server deployment

on:
  push:
    branches: [staging]

env:
  # For the purpose of demo it will use dev project as well here (ideally it should use "staging" env)
  PROJECT_ID: allsaints-cloud-dev
  IMAGE: golang-flux-test

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Assign extracted release version tag
      - name: Extract release branch version tag
        id: release_version_tag_assignment
        run: echo "::set-output name=RELEASE_VERSION_TAG::$(git log -1 --pretty=%B | awk -F '\\\\n' '{print $1}' |  awk -F '/' '{print $3}' | awk '{print $1}')"

      # Setup gcloud CLI with deployment service account
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: allsaints-cloud-dev

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - name: Configure docker instance
        run: |-
          gcloud --quiet auth configure-docker

      # Check if image with requested version exists
      - name: Validate image version if exists
        run: docker image inspect ${{ env.IMAGE }}:${{ steps.release_version_tag_assignment.outputs.RELEASE_VERSION_TAG }} &> /dev/null

      # # Build the Docker image
      # - name: Build
      #   run: |-
      #     docker build \
      #       --tag "gcr.io/$PROJECT_ID/$IMAGE:${{ steps.release_version_tag_assignment.outputs.RELEASE_VERSION_TAG }}" \
      #       --build-arg GITHUB_SHA="$GITHUB_SHA" \
      #       --build-arg GITHUB_REF="$GITHUB_REF" \
      #       .

      # # Push the Docker image to Google Container Registry
      # - name: Publish
      #   run: |-
      #     docker push "gcr.io/$PROJECT_ID/$IMAGE:${{ steps.release_version_tag_assignment.outputs.RELEASE_VERSION_TAG }}"

      # # Update image tag for develop branch
      # - name: Update image hash
      #   run: sed -i "s/golang-flux-test:.*/golang-flux-test:${{ steps.release_version_tag_assignment.outputs.RELEASE_VERSION_TAG }}/g" ./kubernetes/deployment.yaml

      # # Add github email & name
      # - name: Add Github email
      #   run: git config --global user.email "ssitko@pgs-soft.com"; git config --global user.name "ssitko"

      # # Add changes
      # - name: Add current repo / deployment manifest changes
      #   run: git add kubernetes/deployment.yaml

      # # Commit changes
      # - name: Commit changed manifest files
      #   run: git commit -m "Auto updating test.yml k8s manifest"

      # # Fetch test branch
      # - name: Fetch from test
      #   run: git fetch origin test

      # # Push updated manifest
      # - name: Push code to test
      #   run: git push origin HEAD:test
